### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminidor** [linuxeye/bypanel#3]
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 15 total children
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 17 total children
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 19 total children
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), 

之前用elementor 去编辑wordpress 首页，不会卡顿，但现在连保存都成问题

**Comment by linuxeye** [comment]
是不是安装了很多wordpress插件或者访问有链接被墙的url？

**Comment by adminidor** [comment]
插件还好，不多，服务器在硅谷，这个可以排除
主要是另外一台服务器配置还低，2核2G，感觉不到卡，这台2核4G反而卡顿

**Comment by linuxeye** [comment]
问题定位到了吗？
