### ISSUE TITLE
大佬，mirrors.linuxeye.com/lnmp-full.tar.gz 这个包，什么时候换个高带宽的站点吧

### ISSUE THREAD

**Issue by ipme** [linuxeye/bypanel#4]
下载这个镜像包，速度太慢了， 700KB/S ， 这几天有黑五的活动，搞个年付主机，换个高带宽的吧。。

one那个包，你没有维护，也不敢用了，，

**Comment by linuxeye** [comment]
https://downloads.sourceforge.net/project/linuxeye/lnmp-full.tar.gz
