### ISSUE TITLE
两个问题！

### ISSUE THREAD

**Issue by handlegpt** [linuxeye/bypanel#5]
刚搭建完，有一台服务器提示WARN[0000] The "d9rk" variable is not set. Defaulting to a blank string.

进入数据库容器，想登录root时，提示错误ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)       我确认密码是没错的，重新设置，还是无法进入，另外的服务器也这样

**Comment by linuxeye** [comment]
bypanel exec mysql bash
mysql -uroot -pdbrootpwd 
密码进不去吗 ？ 什么操作系统？

**Comment by handlegpt** [comment]
8.0，一台重新pull后，可以进入，另外一台还是不行，但是换成5.7就没问题...

**Comment by handlegpt** [comment]
我想问一下这个支持安装其它php扩展吗

**Comment by linuxeye** [comment]
支持PHP扩展包括：
```
"amqp", "apcu", "bcmath", "bz2", "calendar", "dba", "enchant", "exif", "ffi", "gd", "gettext", "gmp", "igbinary", "imagick", "imap", "intl", "ioncube", "ldap", "lz4", "lzf", "memcache", "memcached", "mongo", "mongodb", "msgpack", "mysqli", "oauth", "oci8", "opcache", "pcntl", "pdo_dblib", "pdo_firebird", "pdo_mysql", "pdo_oci", "pdo_pgsql", "pdo_sqlsrv", "pgsql", "phalcon", "pspell", "psr", "rdkafka", "redis", "shmop", "snmp", "soap", "sockets", "sodium", "solr", "sqlsrv", "swoole", "swoole_loader", "sysvmsg", "sysvsem", "sysvshm", "tidy", "uploadprogress", "uuid", "vips", "xdebug", "xhprof", "xlswriter", "xsl", "yaml", "zip", "zstd"
```
有其他扩展需求可以和我提哦，我加上

**Comment by handlegpt** [comment]
<img width="696" alt="Screenshot 2024-12-05 at 15 51 33" src="https://github.com/user-attachments/assets/833f36d4-97ab-4fd8-900d-d9a0a530c3d6">
如果有些扩展能自定义安装比较好，因为有些服务器也不一定要装

**Comment by linuxeye** [comment]
这些插件现在都支持了，扩展插件是可以通过/opt/bypanel/.env 参数控制：
PHP_MODULES_ENABLE: PHP启用模块，以逗号隔开
PHP_MODULES_DISABLE:PHP禁用模块，以逗号隔开
如果一个模块比如redis在PHP_MODULES_ENABLE和PHP_MODULES_DISABLE都添加，禁用优先
或通过bypanel upgrade
bypanel configure 可配置启用和禁用PHP模块。
