### ISSUE TITLE
使用 Let's Encrypt 证书过期，有没有在现有环境中续期？

### ISSUE THREAD

**Issue by M69W** [linuxeye/bypanel#6]
Let's Encrypt 每三个月过期，有没有自动续期的处理？
当 再次 `bypanel vhost add` 时，提示`Input Error, Please try again, Error: The domain name xxxxxxx.com has been bound`

**Comment by M69W** [comment]
```bypanel upgrade```
然后在 opt/bypanel/README-CN.md 看操作步骤
### SSL证书管理
#### 添加
```
bypanel scm add
```
#### 删除
```
bypanel scm del
```
#### 列表
```
bypanel scm list
```

**Comment by linuxeye** [comment]
默认会自动需求，日志参考：/opt/bypanel/logs/ssl/

**Comment by M69W** [comment]
> 默认会自动续期（证书到期时间剩余1个月自动续期），日志参考：/opt/bypanel/logs/ssl/

补充一下，不知道新版是否是否也这样？
签名续期确实是自动的，但需要手动重启服务使其生效。

**Comment by andymachs** [comment]
> > 默认会自动续期（证书到期时间剩余1个月自动续期），日志参考：/opt/bypanel/logs/ssl/
> 
> 补充一下，不知道新版是否是否也这样？ 签名续期确实是自动的，但需要手动重启服务使其生效。

我也遇到同样的问题：签名续期自动续签了，但是网页上却显示证书还是过期的，需要重启服务器才能使其生效。
所以，作者需要解决一下证书自动续签成功后再重启服务的功能，不然就是一直不生效的。

**Comment by andymachs** [comment]
这个方法是针对nginx的吧，如果是apache或者其他软件呢？这个方法不是无效了吗？

**Comment by andymachs** [comment]
> 之前逻辑更新证书后`nginx -s reload`, 现在改成重启，升级`bypanel upgrade`生效

改成重启主机的话，会不会太激进了？像阿里云这些主机如果要重启的话需要提供手机验证码的，
为了使得续签证书后能离开生效，执行：restart nginx 或者reload nginx, 看哪个命令保证100%有效就可以了，不建议重启主机。

**Comment by linuxeye** [comment]
是改成重启nginx或者apache哦。
